### ISSUE TITLE
Fautes d'orthographe.

### ISSUE THREAD

**Issue by emxjay** [ClementBouche/shifumi#3]
Quelques fautes d'orthographe, vues sur le site :
- _Rechercher un **jeu**.._
- _**Tapez** votre commentaire.._
- _Le profil **n**'est associé **à** aucun **joueur**.._
- _..recherche**z-le** dans la liste des joueurs.._
- _L'**icône** du site est **réalisée**.._
-  _Toutes les données sur les jeux de société sont **récupérées**.._

:v: :doughnut:

**Comment by cboucheIGN** [comment]
the job is done, will be release soon

**Comment by ClementBouche** [comment]
The job is done
